###################  guns配置  ###################
guns:
  swagger-open: true  #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
#  file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  log:
    path: guns-logs

###################  项目启动端口  ###################
server:
  port: 8080

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false


###################  spring配置  ###################
spring:
  profiles:
    active: @spring.active@
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.modular.system.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    db-name: guns
    filters: wall,mergeStat

#多数据源配置
guns:
  muti-datasource:
    url: jdbc:mysql://127.0.0.1:3306/guns2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    defaultDataSourceName: dataSourceGuns #默认的数据源名称

---

spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
      filters: wall,mergeStat

